name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes unitários
        run: npm test -- --watchAll=false

      - name: Rodar testes E2E (Cypress)
        run: |
          npx cypress install
          npm run cy:run

      - name: Build de produção
        run: npm run build
